### ISSUE TITLE
Installation docs

### ISSUE THREAD

**Issue by rafmudaf** [kegiljarhus/pyBEMT#1]
It would be more straightforward to show the installation procedures in two sequential steps:

1. Install the dependencies (i.e. the `pip` command you currently have included or by any other means)
2. Add pyBEMT to the Python path (i.e. `python setup.py install` or `pip install -e .`)

Its a somewhat minor detail but will make the installation process more complete. As is, it may not be clear to a novice user whether the `python setup.py install` command will install the dependencies.

This is in reference to the JOSS review: https://github.com/openjournals/joss-reviews/issues/2480.

**Comment by kegiljarhus** [comment]
Thank you for the suggestion. This has been implemented in commit 97a4b1698462537218842415df5d3590e0b7ed90
