### ISSUE TITLE
About airfoil data

### ISSUE THREAD

**Issue by HYB777** [kegiljarhus/pyBEMT#6]
The airfoil data can be attain by xfoil, and usually we set the chord length equal 1 in xfoil, but in the config.ini, the chord length does not equal 1, should I change the chord length in xfoil setting?

And another problem is should I set different reynold number in each section?

**Comment by kegiljarhus** [comment]
The xfoil chord length is non-dimensional, in the BEMT solver you need to input the real chord length of your propeller/turbine. The actual Reynolds number will depend on other simulation parameters such as the inflow speed and rotational speed, it is output from the simulation. pyBEMT does not currently support multiple airfoil data for different Reynolds numbers, so you need to make some reasonable compromises here.

**Comment by HYB777** [comment]
Thank you for your reply, I think I know how to deal with it
